/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PocketPocketIdImport } from './routes/pocket/$pocketId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PocketPocketIdRoute = PocketPocketIdImport.update({
  id: '/pocket/$pocketId',
  path: '/pocket/$pocketId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pocket/$pocketId': {
      id: '/pocket/$pocketId'
      path: '/pocket/$pocketId'
      fullPath: '/pocket/$pocketId'
      preLoaderRoute: typeof PocketPocketIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pocket/$pocketId': typeof PocketPocketIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pocket/$pocketId': typeof PocketPocketIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pocket/$pocketId': typeof PocketPocketIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pocket/$pocketId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pocket/$pocketId'
  id: '__root__' | '/' | '/pocket/$pocketId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PocketPocketIdRoute: typeof PocketPocketIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PocketPocketIdRoute: PocketPocketIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pocket/$pocketId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pocket/$pocketId": {
      "filePath": "pocket/$pocketId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
