// Generated by Wrangler by running `wrangler types`

interface Env {
	API_BASE_URL: "https://budget-planner-api.cihadaydemir.workers.dev/";
	CLIENT_BASE_URL: "https://budget-planner-bwm.pages.dev/";
	devDB: D1Database;
}
