// Generated by Wrangler by running `wrangler types`

interface Env {
	API_BASE_URL: "https://budget-planner-api.cihadaydemir.workers.dev/";
	CLIENT_BASE_URL: "https://budget-planner-bwm.pages.dev/";
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	devDB: D1Database;
}
